use_frameworks!
target 'LightMooc'  do
  pod 'Masonry', '~> 1.0.2'
  pod 'FMDB', '~> 2.6.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SSZipArchive', '~> 1.8.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'JSONModel', '~> 1.7.0'
  pod 'NullSafe'
  pod 'MJRefresh'
  pod 'YYModel'
  pod ‘Bugly’
  pod 'BEMCheckBox'
  pod 'Socket.IO-Client-Swift', '~> 12.1.3'
end
